apiVersion: apps/v1
kind: Deployment
metadata:
  name: angulist-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angulist-app
  template:
    metadata:
      labels:
        app: angulist-app
    spec:
      containers:
        - name: angulist-app
          image: us.icr.io/hands-on/angulist-app
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angulist-app
  labels:
    app: angulist-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: angulist-app
